### ISSUE TITLE
Using Web Components to reduce the amount of reused code

### ISSUE THREAD

**Issue by matthewghuang** [TempletonRobotics7190/TempletonRobotics7190.github.io#10]
**Issue**: If we need to update the footer or header we need to do it across all files which can become quite tedious.

**Proposed Solution**: Web Components

[webcomponents](https://www.webcomponents.org/)
[polyfills](https://www.webcomponents.org/polyfills)

**Other Solutions**: [Google's Polymer Project](https://www.polymer-project.org/)

**Comment by kx-chen** [comment]
webcomponents and Polymer look pretty good. Somewhat worried about the accessibility and long term adoption of it. Thoughts about using a website generator like Hugo, Jekyll, etc.?

**Comment by matthewghuang** [comment]
I'll do some reading on website generators and get back to you later.

**Comment by matthewghuang** [comment]
Hugo looks nice, if we hook it up to a CMS it looks like it would be great for long-term use.

**Comment by kx-chen** [comment]
Yup, I quite like Hugo as well.

**Comment by kx-chen** [comment]
Code reuse is now reduced with the footer and header files in the Hugo site.
